# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.56648173 0.57525026 0.21772357 0.8560376  0.34833551]
 [0.16408508 0.33230965 0.37536186 0.11525596 0.11032354]
 [0.75865021 0.84931679 0.98223333 0.15649232 0.82282033]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]

[[ 0.24767603 -0.3903775   0.31336765 -0.29344641 -1.52663717]
 [-1.16755015  1.29027034  0.65929044  0.0854544  -0.80995222]
 [ 0.37504327  0.16716451 -0.25493818  0.93909139  1.15588018]
 [-2.54686642 -2.26654391 -1.32442999  1.60543944 -0.25915639]
 [-0.20640823 -0.26129201 -0.00504247  0.84583267 -1.37673011]
 [ 0.17936266  1.18467218  0.40154167 -1.57658851  0.80964308]
 [ 1.42258476 -0.65644346  0.48077832  0.74644394  0.3897596 ]
 [-1.35338148  0.45457233 -2.53234825 -0.23840845  1.08147922]
 [ 1.07087919  0.7536072   0.11520541  0.93715368 -0.24910259]
 [ 3.60172754  0.97063524  0.97071434 -2.25926026 -0.45958852]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4492017190588261
1.1719266973326894


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.010254483643500567
3.6017275425619424


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.17203268  0.24128495 -0.34253239  1.03023487 -0.00932064  0.26187282
 -0.8088498  -0.98184431  0.29676974  0.69715431 -0.47361636 -0.39443966
  1.42323363 -0.40167291 -1.80152525 -2.03912067  0.0958742  -1.13912123
  0.22707992]
-0.8088497986122875


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.00932064  0.26187282 -0.8088498  -0.98184431  0.29676974]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.17203268  1.03023487 -0.8088498   0.69715431  1.42323363]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.56648173 0.57525026 0.21772357 0.8560376  0.34833551]
 [0.16408508 0.33230965 0.37536186 0.11525596 0.11032354]
 [0.75865021 0.84931679 0.98223333 0.15649232 0.82282033]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]
0.37536185544619716
0.37536185544619716


In [19]:
print(rand_mat[0:2,1:3])

[[0.57525026 0.21772357]
 [0.33230965 0.37536186]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.17203268  0.24128495 -0.34253239  1.03023487 -0.00932064  0.26187282
 -0.8088498  -0.98184431  0.29676974  0.69715431 -0.47361636 -0.39443966
  1.42323363 -0.40167291 -1.80152525 -2.03912067  0.0958742  -1.13912123
  0.22707992]

[ 0.17203268  0.24128495 -0.34253239  4.          4.          0.26187282
 -0.8088498  -0.98184431  0.29676974  0.69715431 -0.47361636 -0.39443966
  1.42323363 -0.40167291 -1.80152525 -2.03912067  0.0958742  -1.13912123
  0.22707992]

[ 0.17203268  0.24128495 -0.34253239  1.          2.          0.26187282
 -0.8088498  -0.98184431  0.29676974  0.69715431 -0.47361636 -0.39443966
  1.42323363 -0.40167291 -1.80152525 -2.03912067  0.0958742  -1.13912123
  0.22707992]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.56648173 0.57525026 0.21772357 0.8560376  0.34833551]
 [0.16408508 0.33230965 0.37536186 0.11525596 0.11032354]
 [0.75865021 0.84931679 0.98223333 0.15649232 0.82282033]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]

[[0.56648173 0.57525026 0.21772357 0.8560376  0.34833551]
 [0.16408508 0.33230965 0.37536186 0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.56648173 0.57525026 0.21772357]
 [0.16408508 0.33230965 0.37536186]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.         3.         0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.         3.         0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.96461532  0.12772804  0.1883827   0.47527416  0.0746983   0.25876041
 -0.15720421  0.23837439  1.06363383 -0.88688253  2.44228023 -1.27396056
 -1.06478304 -0.40273077 -2.72598353]
[ True  True  True  True  True  True False  True  True False  True False
 False False False]
[0.96461532 0.12772804 0.1883827  0.47527416 0.0746983  0.25876041
 0.23837439 1.06363383 2.44228023]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.24767603 -0.3903775   0.31336765 -0.29344641 -1.52663717]
 [-1.16755015  1.29027034  0.65929044  0.0854544  -0.80995222]
 [ 0.37504327  0.16716451 -0.25493818  0.93909139  1.15588018]
 [-2.54686642 -2.26654391 -1.32442999  1.60543944 -0.25915639]
 [-0.20640823 -0.26129201 -0.00504247  0.84583267 -1.37673011]
 [ 0.17936266  1.18467218  0.40154167 -1.57658851  0.80964308]
 [ 1.42258476 -0.65644346  0.48077832  0.74644394  0.3897596 ]
 [-1.35338148  0.45457233 -2.53234825 -0.23840845  1.08147922]
 [ 1.07087919  0.7536072   0.11520541  0.93715368 -0.24910259]
 [ 3.60172754  0.97063524  0.97071434 -2.25926026 -0.45958852]]
[0.24767603 0.31336765 1.29027034 0.65929044 0.0854544  0.37504327
 0.16716451 0.93909139 1.15588018 1.60543944 0.84583267 0.17936266
 1.18467218 0.40154167 0.80964308 1.42258476 0.48077832 0.74644394
 0.3897596  0.45457233 1.08147922 1.07087919 0.7536072  0.11520541
 0.93715368 3.60172754 0.97063524 0.97071434]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.96461532  0.12772804  0.1883827   0.47527416  0.0746983   0.25876041
 -0.15720421  0.23837439  1.06363383 -0.88688253  2.44228023 -1.27396056
 -1.06478304 -0.40273077 -2.72598353]

[-5.          0.12772804  0.1883827   0.47527416  0.0746983   0.25876041
 -0.15720421  0.23837439 -5.         -0.88688253 -5.         -1.27396056
 -1.06478304 -0.40273077 -2.72598353]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.24767603 -0.3903775   0.31336765 -0.29344641 -1.52663717]
 [-1.16755015  1.29027034  0.65929044  0.0854544  -0.80995222]
 [ 0.37504327  0.16716451 -0.25493818  0.93909139  1.15588018]
 [-2.54686642 -2.26654391 -1.32442999  1.60543944 -0.25915639]
 [-0.20640823 -0.26129201 -0.00504247  0.84583267 -1.37673011]
 [ 0.17936266  1.18467218  0.40154167 -1.57658851  0.80964308]
 [ 1.42258476 -0.65644346  0.48077832  0.74644394  0.3897596 ]
 [-1.35338148  0.45457233 -2.53234825 -0.23840845  1.08147922]
 [ 1.07087919  0.7536072   0.11520541  0.93715368 -0.24910259]
 [ 3.60172754  0.97063524  0.97071434 -2.25926026 -0.45958852]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.         3.         0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]

[[ 0.24767603 -0.3903775   0.31336765 -0.29344641 -1.52663717]
 [-1.16755015  1.29027034  0.65929044  0.0854544  -0.80995222]
 [ 0.37504327  0.16716451 -0.25493818  0.93909139  1.15588018]
 [-2.54686642 -2.26654391 -1.32442999  1.60543944 -0.25915639]
 [-0.20640823 -0.26129201 -0.00504247  0.84583267 -1.37673011]
 [ 0.17936266  1.18467218  0.40154167 -1.57658851  0.80964308]
 [ 1.42258476 -0.65644346  0.48077832  0.74644394  0.3897596 ]
 [-1.35338148  0.45457233 -2.53234825 -0.23840845  1.08147922]
 [ 1.07087919  0.7536072   0.11520541  0.93715368 -0.24910259]
 [ 3.60172754  0.97063524  0.97071434 -2.25926026 -0.45958852]]
[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.         3.         0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]

[[3.         3.         3.         0.8560376  0.34833551]
 [3.         3.         3.         0.         0.        ]
 [0.75865021 0.84931679 0.98223333 0.         0.        ]
 [0.42314158 0.04074405 0.37031034 0.1529982  0.90434598]
 [0.92960288 0.16667406 0.31704137 0.01025448 0.68425227]]
